// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: schema/finish_file_transfer/finish_file_transfer.proto

package finish_file_transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinishFileUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodeId string `protobuf:"bytes,1,opt,name=data_node_id,json=dataNodeId,proto3" json:"data_node_id,omitempty"`
	FileName   string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FilePath   string `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *FinishFileUploadRequest) Reset() {
	*x = FinishFileUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishFileUploadRequest) ProtoMessage() {}

func (x *FinishFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishFileUploadRequest.ProtoReflect.Descriptor instead.
func (*FinishFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *FinishFileUploadRequest) GetDataNodeId() string {
	if x != nil {
		return x.DataNodeId
	}
	return ""
}

func (x *FinishFileUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FinishFileUploadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type FinishFileUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishFileUploadResponse) Reset() {
	*x = FinishFileUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishFileUploadResponse) ProtoMessage() {}

func (x *FinishFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishFileUploadResponse.ProtoReflect.Descriptor instead.
func (*FinishFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescGZIP(), []int{1}
}

var File_schema_finish_file_transfer_finish_file_transfer_proto protoreflect.FileDescriptor

var file_schema_finish_file_transfer_finish_file_transfer_proto_rawDesc = []byte{
	0x0a, 0x36, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x75,
	0x0a, 0x17, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x1a, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x46,
	0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x8e, 0x01, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x71, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x2d, 0x2e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x66, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescOnce sync.Once
	file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescData = file_schema_finish_file_transfer_finish_file_transfer_proto_rawDesc
)

func file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescGZIP() []byte {
	file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescOnce.Do(func() {
		file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescData)
	})
	return file_schema_finish_file_transfer_finish_file_transfer_proto_rawDescData
}

var file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_finish_file_transfer_finish_file_transfer_proto_goTypes = []interface{}{
	(*FinishFileUploadRequest)(nil),  // 0: finish_file_transfer.FinishFileUploadRequest
	(*FinishFileUploadResponse)(nil), // 1: finish_file_transfer.FinishFileUploadResponse
}
var file_schema_finish_file_transfer_finish_file_transfer_proto_depIdxs = []int32{
	0, // 0: finish_file_transfer.FinishFileTransferService.FinishFileUpload:input_type -> finish_file_transfer.FinishFileUploadRequest
	1, // 1: finish_file_transfer.FinishFileTransferService.FinishFileUpload:output_type -> finish_file_transfer.FinishFileUploadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_finish_file_transfer_finish_file_transfer_proto_init() }
func file_schema_finish_file_transfer_finish_file_transfer_proto_init() {
	if File_schema_finish_file_transfer_finish_file_transfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishFileUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishFileUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_finish_file_transfer_finish_file_transfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_finish_file_transfer_finish_file_transfer_proto_goTypes,
		DependencyIndexes: file_schema_finish_file_transfer_finish_file_transfer_proto_depIdxs,
		MessageInfos:      file_schema_finish_file_transfer_finish_file_transfer_proto_msgTypes,
	}.Build()
	File_schema_finish_file_transfer_finish_file_transfer_proto = out.File
	file_schema_finish_file_transfer_finish_file_transfer_proto_rawDesc = nil
	file_schema_finish_file_transfer_finish_file_transfer_proto_goTypes = nil
	file_schema_finish_file_transfer_finish_file_transfer_proto_depIdxs = nil
}
