// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: schema/replicate/replicate.proto

package replicate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Master Notify DST
type NotifyToCopyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SrcAddress string `protobuf:"bytes,2,opt,name=src_address,json=srcAddress,proto3" json:"src_address,omitempty"`
}

func (x *NotifyToCopyRequest) Reset() {
	*x = NotifyToCopyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyToCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyToCopyRequest) ProtoMessage() {}

func (x *NotifyToCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyToCopyRequest.ProtoReflect.Descriptor instead.
func (*NotifyToCopyRequest) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyToCopyRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *NotifyToCopyRequest) GetSrcAddress() string {
	if x != nil {
		return x.SrcAddress
	}
	return ""
}

type NotifyToCopyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *NotifyToCopyResponse) Reset() {
	*x = NotifyToCopyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyToCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyToCopyResponse) ProtoMessage() {}

func (x *NotifyToCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyToCopyResponse.ProtoReflect.Descriptor instead.
func (*NotifyToCopyResponse) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyToCopyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DST want to copy from SRC
type CopyingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *CopyingRequest) Reset() {
	*x = CopyingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyingRequest) ProtoMessage() {}

func (x *CopyingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyingRequest.ProtoReflect.Descriptor instead.
func (*CopyingRequest) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{2}
}

func (x *CopyingRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CopyingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*CopyingResponse_FileInfo
	//	*CopyingResponse_ChuckData
	Data isCopyingResponse_Data `protobuf_oneof:"data"`
}

func (x *CopyingResponse) Reset() {
	*x = CopyingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyingResponse) ProtoMessage() {}

func (x *CopyingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyingResponse.ProtoReflect.Descriptor instead.
func (*CopyingResponse) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{3}
}

func (m *CopyingResponse) GetData() isCopyingResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *CopyingResponse) GetFileInfo() *FileInfo {
	if x, ok := x.GetData().(*CopyingResponse_FileInfo); ok {
		return x.FileInfo
	}
	return nil
}

func (x *CopyingResponse) GetChuckData() []byte {
	if x, ok := x.GetData().(*CopyingResponse_ChuckData); ok {
		return x.ChuckData
	}
	return nil
}

type isCopyingResponse_Data interface {
	isCopyingResponse_Data()
}

type CopyingResponse_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type CopyingResponse_ChuckData struct {
	ChuckData []byte `protobuf:"bytes,2,opt,name=chuck_data,json=chuckData,proto3,oneof"`
}

func (*CopyingResponse_FileInfo) isCopyingResponse_Data() {}

func (*CopyingResponse_ChuckData) isCopyingResponse_Data() {}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// DST Comfirm copying
type ConfirmCopyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	NodeId   string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *ConfirmCopyRequest) Reset() {
	*x = ConfirmCopyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmCopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCopyRequest) ProtoMessage() {}

func (x *ConfirmCopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCopyRequest.ProtoReflect.Descriptor instead.
func (*ConfirmCopyRequest) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmCopyRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ConfirmCopyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ConfirmCopyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ConfirmCopyResponse) Reset() {
	*x = ConfirmCopyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_replicate_replicate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCopyResponse) ProtoMessage() {}

func (x *ConfirmCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_replicate_replicate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCopyResponse.ProtoReflect.Descriptor instead.
func (*ConfirmCopyResponse) Descriptor() ([]byte, []int) {
	return file_schema_replicate_replicate_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmCopyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_schema_replicate_replicate_proto protoreflect.FileDescriptor

var file_schema_replicate_replicate_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x53, 0x0a,
	0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x72, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x43, 0x6f,
	0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x2d, 0x0a, 0x0e, 0x43, 0x6f, 0x70, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x6e, 0x0a, 0x0f, 0x43, 0x6f, 0x70, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x63,
	0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09,
	0x63, 0x68, 0x75, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x27, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xf5, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x1e, 0x2e, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x43,
	0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x43,
	0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x43,
	0x6f, 0x70, 0x79, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f,
	0x70, 0x79, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x4c, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x6f, 0x70, 0x79, 0x12, 0x1d,
	0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a,
	0x10, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_replicate_replicate_proto_rawDescOnce sync.Once
	file_schema_replicate_replicate_proto_rawDescData = file_schema_replicate_replicate_proto_rawDesc
)

func file_schema_replicate_replicate_proto_rawDescGZIP() []byte {
	file_schema_replicate_replicate_proto_rawDescOnce.Do(func() {
		file_schema_replicate_replicate_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_replicate_replicate_proto_rawDescData)
	})
	return file_schema_replicate_replicate_proto_rawDescData
}

var file_schema_replicate_replicate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_schema_replicate_replicate_proto_goTypes = []interface{}{
	(*NotifyToCopyRequest)(nil),  // 0: replicate.NotifyToCopyRequest
	(*NotifyToCopyResponse)(nil), // 1: replicate.NotifyToCopyResponse
	(*CopyingRequest)(nil),       // 2: replicate.CopyingRequest
	(*CopyingResponse)(nil),      // 3: replicate.CopyingResponse
	(*FileInfo)(nil),             // 4: replicate.FileInfo
	(*ConfirmCopyRequest)(nil),   // 5: replicate.ConfirmCopyRequest
	(*ConfirmCopyResponse)(nil),  // 6: replicate.ConfirmCopyResponse
}
var file_schema_replicate_replicate_proto_depIdxs = []int32{
	4, // 0: replicate.CopyingResponse.file_info:type_name -> replicate.FileInfo
	0, // 1: replicate.ReplicateService.NotifyToCopy:input_type -> replicate.NotifyToCopyRequest
	2, // 2: replicate.ReplicateService.Copying:input_type -> replicate.CopyingRequest
	5, // 3: replicate.ReplicateService.ConfirmCopy:input_type -> replicate.ConfirmCopyRequest
	1, // 4: replicate.ReplicateService.NotifyToCopy:output_type -> replicate.NotifyToCopyResponse
	3, // 5: replicate.ReplicateService.Copying:output_type -> replicate.CopyingResponse
	6, // 6: replicate.ReplicateService.ConfirmCopy:output_type -> replicate.ConfirmCopyResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_replicate_replicate_proto_init() }
func file_schema_replicate_replicate_proto_init() {
	if File_schema_replicate_replicate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_replicate_replicate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyToCopyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyToCopyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmCopyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_replicate_replicate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmCopyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_schema_replicate_replicate_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*CopyingResponse_FileInfo)(nil),
		(*CopyingResponse_ChuckData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_replicate_replicate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_replicate_replicate_proto_goTypes,
		DependencyIndexes: file_schema_replicate_replicate_proto_depIdxs,
		MessageInfos:      file_schema_replicate_replicate_proto_msgTypes,
	}.Build()
	File_schema_replicate_replicate_proto = out.File
	file_schema_replicate_replicate_proto_rawDesc = nil
	file_schema_replicate_replicate_proto_goTypes = nil
	file_schema_replicate_replicate_proto_depIdxs = nil
}
