// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: schema/register/register.proto

package register

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataKeeperRegisterServiceClient is the client API for DataKeeperRegisterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataKeeperRegisterServiceClient interface {
	Register(ctx context.Context, in *DataKeeperRegisterRequest, opts ...grpc.CallOption) (*DataKeeperRegisterResponse, error)
}

type dataKeeperRegisterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataKeeperRegisterServiceClient(cc grpc.ClientConnInterface) DataKeeperRegisterServiceClient {
	return &dataKeeperRegisterServiceClient{cc}
}

func (c *dataKeeperRegisterServiceClient) Register(ctx context.Context, in *DataKeeperRegisterRequest, opts ...grpc.CallOption) (*DataKeeperRegisterResponse, error) {
	out := new(DataKeeperRegisterResponse)
	err := c.cc.Invoke(ctx, "/register.DataKeeperRegisterService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataKeeperRegisterServiceServer is the server API for DataKeeperRegisterService service.
// All implementations must embed UnimplementedDataKeeperRegisterServiceServer
// for forward compatibility
type DataKeeperRegisterServiceServer interface {
	Register(context.Context, *DataKeeperRegisterRequest) (*DataKeeperRegisterResponse, error)
	mustEmbedUnimplementedDataKeeperRegisterServiceServer()
}

// UnimplementedDataKeeperRegisterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataKeeperRegisterServiceServer struct {
}

func (UnimplementedDataKeeperRegisterServiceServer) Register(context.Context, *DataKeeperRegisterRequest) (*DataKeeperRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDataKeeperRegisterServiceServer) mustEmbedUnimplementedDataKeeperRegisterServiceServer() {
}

// UnsafeDataKeeperRegisterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataKeeperRegisterServiceServer will
// result in compilation errors.
type UnsafeDataKeeperRegisterServiceServer interface {
	mustEmbedUnimplementedDataKeeperRegisterServiceServer()
}

func RegisterDataKeeperRegisterServiceServer(s grpc.ServiceRegistrar, srv DataKeeperRegisterServiceServer) {
	s.RegisterService(&DataKeeperRegisterService_ServiceDesc, srv)
}

func _DataKeeperRegisterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataKeeperRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataKeeperRegisterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/register.DataKeeperRegisterService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataKeeperRegisterServiceServer).Register(ctx, req.(*DataKeeperRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataKeeperRegisterService_ServiceDesc is the grpc.ServiceDesc for DataKeeperRegisterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataKeeperRegisterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "register.DataKeeperRegisterService",
	HandlerType: (*DataKeeperRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DataKeeperRegisterService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/register/register.proto",
}
