// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: schema/confirm_file_transfer/confirm_file_transfer.proto

package confirm_file_transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmFileTransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *ConfirmFileTransferRequest) Reset() {
	*x = ConfirmFileTransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmFileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmFileTransferRequest) ProtoMessage() {}

func (x *ConfirmFileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmFileTransferRequest.ProtoReflect.Descriptor instead.
func (*ConfirmFileTransferRequest) Descriptor() ([]byte, []int) {
	return file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmFileTransferRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ConfirmFileTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfirmFileTransferResponse) Reset() {
	*x = ConfirmFileTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmFileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmFileTransferResponse) ProtoMessage() {}

func (x *ConfirmFileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmFileTransferResponse.ProtoReflect.Descriptor instead.
func (*ConfirmFileTransferResponse) Descriptor() ([]byte, []int) {
	return file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescGZIP(), []int{1}
}

var File_schema_confirm_file_transfer_confirm_file_transfer_proto protoreflect.FileDescriptor

var file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDesc = []byte{
	0x0a, 0x38, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x22, 0x39, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x69, 0x6c, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x1b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9a, 0x01, 0x0a, 0x1a,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7c, 0x0a, 0x13, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x12, 0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescOnce sync.Once
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescData = file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDesc
)

func file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescGZIP() []byte {
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescOnce.Do(func() {
		file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescData)
	})
	return file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDescData
}

var file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_confirm_file_transfer_confirm_file_transfer_proto_goTypes = []interface{}{
	(*ConfirmFileTransferRequest)(nil),  // 0: confirm_file_transfer.ConfirmFileTransferRequest
	(*ConfirmFileTransferResponse)(nil), // 1: confirm_file_transfer.ConfirmFileTransferResponse
}
var file_schema_confirm_file_transfer_confirm_file_transfer_proto_depIdxs = []int32{
	0, // 0: confirm_file_transfer.ConfirmFileTransferService.ConfirmFileTransfer:input_type -> confirm_file_transfer.ConfirmFileTransferRequest
	1, // 1: confirm_file_transfer.ConfirmFileTransferService.ConfirmFileTransfer:output_type -> confirm_file_transfer.ConfirmFileTransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_confirm_file_transfer_confirm_file_transfer_proto_init() }
func file_schema_confirm_file_transfer_confirm_file_transfer_proto_init() {
	if File_schema_confirm_file_transfer_confirm_file_transfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmFileTransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmFileTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_confirm_file_transfer_confirm_file_transfer_proto_goTypes,
		DependencyIndexes: file_schema_confirm_file_transfer_confirm_file_transfer_proto_depIdxs,
		MessageInfos:      file_schema_confirm_file_transfer_confirm_file_transfer_proto_msgTypes,
	}.Build()
	File_schema_confirm_file_transfer_confirm_file_transfer_proto = out.File
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_rawDesc = nil
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_goTypes = nil
	file_schema_confirm_file_transfer_confirm_file_transfer_proto_depIdxs = nil
}
